ALTER TABLE `users`
  MODIFY `avatarUrl` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `birthDate` DATE NULL AFTER `avatarUrl`,
  ADD COLUMN IF NOT EXISTS `phone` VARCHAR(30) NULL AFTER `birthDate`,
  ADD COLUMN IF NOT EXISTS `city` VARCHAR(120) NULL AFTER `phone`,
  ADD COLUMN IF NOT EXISTS `bio` TEXT NULL AFTER `city`,
  ADD COLUMN IF NOT EXISTS `gender` ENUM('male', 'female', 'other') NULL AFTER `bio`;
